version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
